export const state =
    [
        // { "code": "AN", "name": "Andaman and Nicobar Islands" },
        { "code": "andhra%20pradesh", "name": "Andhra Pradesh" },
        { "code": "Arunachal%20Pradesh", "name": "Arunachal Pradesh" },
        { "code": "assam", "name": "Assam" },
        { "code": "bihar", "name": "Bihar" },
        { "code": "Chandigarh", "name": "Chandigarh" },
        { "code": "Chhattisgarh", "name": "Chhattisgarh" },
        // { "code": "DH", "name": "Dadra and Nagar Haveli" },
        // { "code": "DD", "name": "Daman and Diu" },
        { "code": "delhi", "name": "Delhi" },
        { "code": "goa", "name": "Goa" },
        { "code": "gujarat", "name": "Gujarat" },
        { "code": "haryana", "name": "Haryana" },
        { "code": "himachal%20pradesh", "name": "Himachal Pradesh" },
        // { "code": "JK", "name": "Jammu and Kashmir" },
        { "code": "jharkhand", "name": "Jharkhand" },
        { "code": "karnataka", "name": "Karnataka" },
        { "code": "kerala", "name": "Kerala" },
        // { "code": "LD", "name": "Lakshadweep" },
        { "code": "madhya%20pradesh", "name": "Madhya Pradesh" },
        { "code": "maharashtra", "name": "Maharashtra" },
        { "code": "Manipur", "name": "Manipur" },
        { "code": "Meghalaya", "name": "Meghalaya" },
        { "code": "Mizoram", "name": "Mizoram" },
        { "code": "Nagaland", "name": "Nagaland" },
        { "code": "orissa", "name": "Odisha" },
        // { "code": "PY", "name": "Puducherry" },
        { "code": "punjab", "name": "Punjab" },
        { "code": "rajasthan", "name": "Rajasthan" },
        { "code": "Sikkim", "name": "Sikkim" },
        { "code": "tamil%20nadu", "name": "Tamil Nadu" },
        { "code": "telangana", "name": "Telangana" },
        { "code": "Tripura", "name": "Tripura" },
        { "code": "Uttarakhand", "name": "Uttarakhand" },
        { "code": "uttar%20pradesh", "name": "Uttar Pradesh" },
        { "code": "west%20bengal", "name": "West Bengal" }
    ]
